name: Deploy static site to VPS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check PHP syntax
        run: |
          find . -name "*.php" -exec php -l {} \;

      - name: Deploy to VPS via rsync
        env:
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          rsync -avz --delete -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ $VPS_USER@$VPS_HOST:/path/to/your/webroot
          rm key.pem
